#!/usr/bin/env python3

from cli import cli_arg_parse
import urllib.request
import json
from utils import create_url, get_repos

# parse CLI arguments
args = cli_arg_parse()
duration = args.duration
limit = args.limit

#url = create_url(duration, limit)
url = "https://api.github.com/search/repositories?q=created%3A%3E2026-04-16&per_page=100&sort=stars&order=desc&page=2"
repos = get_repos(url, limit)
print(len(repos))