#!/usr/bin/env python3

from cli import cli_arg_parse
import urllib.request
from datetime import datetime, timedelta

# parse CLI arguments
args = cli_arg_parse()
duration = args.duration
limit = args.limit

def create_url(duration, limit):
    durations = {
        "day": 1,
        "week": 7,
        "month": 30,
        "year": 365
    }
    today = datetime.today().date()
    start_date = (today - timedelta(days=durations[duration])).isoformat()

    per_page = min(100, limit)
    return f"https://api.github.com/search/repositories?q=created%3A%3E{start_date}&per_page={per_page}&sort=stars&order=desc"

url = create_url(duration, limit)
